#include <iostream>
using namespace std;
/*
	* Problem #2
	* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
	* 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	* By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms
*/
int main() {
	int first = 1, second = 2, third = 3, sum = 2;
	while (third <= 4000000) {
		third = first + second;
		if (third % 2 == 0)
			sum += third;
		first = second;
		second = third;
	}
	cout << sum;
}